/**
 * LankaBuy Server-Generated Order Fulfillment PDF
 *
 * Pure presentational layer over the authoritative Firestore order record.
 * No authorization logic here — the route guard (requireAdminAuth) owns that.
 *
 * NOTE on fonts: pdfkit ships with Latin base fonts (Helvetica). A Sinhala
 * TTF is not bundled with the server, so non-Latin glyphs fall back to
 * blank boxes. Latin-script fulfillment data (supplier forms, addresses as
 * captured at checkout) prints cleanly. If Sinhala print support is needed,
 * drop a NotoSansSinhala TTF next to this module and register it below.
 */

import PDFDocument from 'pdfkit';
import type { Order } from '../src/types.ts';

function safeText(value: unknown): string {
  if (value === undefined || value === null) return '-';
  const s = String(value);
  // Strip control chars that break PDF text operators; keep all scripts.
  return s.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, '').trim() || '-';
}

export function buildOrderPdfBuffer(order: Order): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 48 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const c = order.customer || ({} as any);
      const line = (label: string, value: unknown) => {
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#111111').text(`${label}: `, { continued: true });
        doc.font('Helvetica').fontSize(10).fillColor('#333333').text(safeText(value));
      };
      const section = (title: string) => {
        doc.moveDown(0.8);
        doc.font('Helvetica-Bold').fontSize(13).fillColor('#c2410c').text(title);
        doc.moveDown(0.2);
        doc.strokeColor('#e5e7eb').lineWidth(1)
          .moveTo(doc.page.margins.left, doc.y)
          .lineTo(doc.page.width - doc.page.margins.right, doc.y)
          .stroke();
        doc.moveDown(0.4);
      };

      // Header
      doc.font('Helvetica-Bold').fontSize(22).fillColor('#111111').text('LankaBuy');
      doc.font('Helvetica').fontSize(10).fillColor('#6b7280')
        .text('Order Fulfillment Sheet — Sri Lanka');
      doc.moveDown(0.4);
      line('Order ID', order.orderNumber || order.id);
      line('Internal ID', order.id);
      line('Order Date', order.createdAt ? new Date(order.createdAt).toLocaleString() : '-');
      line('Order Status', order.status || '-');
      line('Payment Status', order.paymentStatus || '-');

      // Product
      section('PRODUCT');
      for (const item of order.items || []) {
        line('Product name', (item as any).title);
        line('Product ID', (item as any).productId);
        line('Quantity', (item as any).quantity);
        line('Supplier', (item as any).supplierOrigin || (item as any).supplierName || '-');
        const supplierUrl = (item as any).cjDirectUrl || (item as any).qksourceUrl || '';
        line('Supplier URL', supplierUrl || '-');
        doc.moveDown(0.3);
      }

      // Customer
      section('CUSTOMER');
      line('Name', c.fullName);
      line('Email', c.email);
      line('Phone', c.phone);
      line('WhatsApp', (c as any).whatsapp || '-');

      // Shipping
      section('SHIPPING');
      line('Recipient', c.fullName);
      const fullAddress = [c.street, c.city, c.district, c.province, c.postalCode]
        .filter((p) => p && String(p).trim())
        .join(', ');
      line('Full shipping address', fullAddress);
      line('Country', c.country);
      line('Province', (c as any).province);
      line('District', c.district);
      line('City', c.city);
      line('Phone', c.phone);
      line('WhatsApp', (c as any).whatsapp || '-');

      // Payment (server-verified values from the stored order record)
      section('PAYMENT');
      line('Payment status', order.paymentStatus);
      line('Creem Checkout ID', (order as any).creemCheckoutId || order.transactionId);
      line('Creem Order ID', (order as any).creemOrderId);
      line('Creem Customer ID', (order as any).creemCustomerId);
      line('Amount', `${safeText((order as any).currency || 'LKR')} ${safeText(order.totalAmount)}`);
      line('Currency', (order as any).currency || 'LKR');
      line('Paid timestamp', (order as any).paidAt);

      section('ORDER STATUS');
      line('Status', order.status);
      line('Inventory', (order as any).inventoryStatus || '-');
      if (order.trackingNumber) line('Tracking', order.trackingNumber);

      doc.moveDown(1);
      doc.font('Helvetica').fontSize(9).fillColor('#9ca3af')
        .text(`Generated by LankaBuy Admin — ${new Date().toLocaleString()}`);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
